---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create VNG
      azure_rm_deployment:
        state: present
        resource_group_name: network
        location: westeurope
        template_link: 'https://raw.githubusercontent.com/mdobrzyn/awx-demo-azure_rm_deployment/master/2-create-vng/azuredeploy.json'
        parameters_link: 'https://raw.githubusercontent.com/mdobrzyn/awx-demo-azure_rm_deployment/master/2-create-vng/azuredeploy.parameters.json'
