---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a resource group for VMs
      azure_rm_resourcegroup:
        name: vms
        location: westeurope
    - name: Create vms with apps
      azure_rm_deployment:
        state: present
        resource_group_name: vms
        location: westeurope
        template_link: 'https://raw.githubusercontent.com/mdobrzyn/awx-demo-azure_rm_deployment/ansiblevar/3-create-windows/azuredeploy.json'
        #parameters_link: 'https://raw.githubusercontent.com/mdobrzyn/awx-demo-azure_rm_deployment/ansiblevar/3-create-windows/azuredeploy.parameters.json'
        parameters:
          virtualMachineAdminUserName:
            value: {{ fromansibleplaybook_virtualMachineAdminUserName }}
          virtualMachineAdminPassword:
            value: {{ fromansibleplaybook_adminPassword }}
          virtualMachineNamePrefix:
            value: {{ fromansibleplaybook_virtualMachineNamePrefix }}
          virtualMachineCount:
            value: 2
          virtualMachineSize:
            value: {{ fromansibleplaybook_virtualMachineSize }}
          operatingSystem:
            value: Server2016
          availabilitySetName: 
            value: avset
          virtualNetworkName:
            value: {{ fromansibleplaybook_virtualNetworkName }}
          virtualNetworkResourceGroup:
            value: {{ fromansibleplaybook_virtualNetworkResourceGroup }}
          subnet1Name:
            value: {{ fromansibleplaybook_subnet1Name }}